- name: install required packages
  apt:
    pkg:
      - sssd-ldap
      - ldap-utils
      - libpam-sss
      - libnss-sss
      - libnss-ldap
      - openssl
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: install required packages
  apt:
    pkg:
      - ldapscripts
    state: present
    update_cache: yes
  when: ansible_distribution == "Ubuntu" and install_ldapscripts|bool

- name: set local name resolution
  lineinfile:
    path: /etc/hosts
    line: '{{ ldap_host_ip }} {{ ldap_host }} {{ ldap_host }}.{{ domain }}'
  when: set_hosts

- name: import certs
  block:
  - name: grab cert from server
    shell: openssl s_client -showcerts -connect {{ ldap_host }}.{{ domain }}:636 </dev/null 2>/dev/null|openssl x509 -outform PEM > /etc/ssl/certs/{{ ldap_host }}.pem
  - name: place cert-file with explicit permissions
    file:
      path: /etc/ssl/certs/{{ ldap_host }}.pem
      owner: root
      group: root
      mode: 0644
  when: ldap_tls

- name: seed sssd config
  template:
    src: sssd.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600
    force: true

- name: pam - autocreate homedirs
  shell: pam-auth-update --enable mkhomedir

- name: restart sssd daemon with new config
  systemd:
    name: sssd.service
    state: restarted

- name: prevent gnome user environment initialization
  blockinfile:
    path: /etc/profile.d/disable-gnome-userinit.sh
    create: true
    mode: '0644'
    block: |
      #!/bin/bash
      # prevent gnome user environment initialization
      
      if [ -d ~/.config ]; then
        echo -n 'yes' >~/.config/gnome-initial-setup-done
      fi

- name: add LDAP based ssh key infrastructure
  import_tasks: ssh.yml
  tags:
    - ldap-ssh